services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - ms-auth
      - ms-ecommerce
      - api-gateway

  mysqldb: # Servicio para MySQL
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=linktic-ecommerce
      - MYSQL_USER=root
      - MYSQL_PASSWORD=''
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ms-auth:
    build:
      context: ./ms-auth
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_NAME=linktic-ecommerce

  ms-ecommerce:
    build:
      context: ./ms-ecommerce
    ports:
      - "8000:80"
    environment:
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_NAME=linktic-ecommerce

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3001:3000"
