version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - api-service
      - node-service

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "5000:5000"

  api-service:
    build:
      context: ./api-service
    ports:
      - "8000:80"

  node-service:
    build:
      context: ./node-service
    ports:
      - "3001:3000"
